---
common:
    title: Generic event with Reordered Fields
    controllerConfigs:
        KGOUIDetail: info.objdefs.detail
    dataObjects:
    -   KGOCalendarEvent
    objdefs:
        detail:
            regions:
            -   name: content
                contents:
                -   class: KGOHTMLController
                    requiresData: true
                    fields:
                        heading:
                        -   kgoResolveType: localize
                            kgoResolveValue: core.ui.calendar.headings.description
                        html:
                        -   kgoResolveType: value
                            kgoResolveValue: kgo:description
                            kgoResolveProcessors:
                            -   class: KGOTrimToNullDataProcessor
                            -   class: KGOHTMLEncodeDataProcessor
                -   class: KGOHTMLController
                    requiresData: true
                    fields:
                        heading:
                        -   kgoResolveType: localize
                            kgoResolveValue: core.ui.calendar.headings.location
                        html:
                        -   kgoResolveType: value
                            kgoResolveValue: kgocalendar:location
                            kgoResolveProcessors:
                            -   class: KGOTrimToNullDataProcessor
                -   class: KGOListController
                    requiresData: true
                    fields:
                        heading:
                        -   kgoResolveType: localize
                            kgoResolveValue: core.ui.calendar.headings.website
                    options:
                        grouped: true
                        inset: true
                    regions:
                    -   name: items
                        contents:
                        -   class: KGOListItemController
                            source:
                            -   kgoResolveType: value
                                kgoResolveValue: kgocalendar:url
                                kgoResolveProcessors:
                                -   class: KGOTrimToNullDataProcessor
                                -   class: KGOURLsToLinksDataProcessor
...
